version: '3.8'

services:
  # База данных
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: postgres
      POSTGRES_DB: music_label
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring_net

  # Мониторинг
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_net
    depends_on:
      - postgres-exporter
      - node-exporter

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring_net
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitoring_net

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring_net

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/music_label?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - monitoring_net
    depends_on:
      - postgres

networks:
  monitoring_net:
    driver: bridge

volumes:
  postgres_data:
  grafana_data: